variable "elastio_pat" {
  description = "Personal Access Token generated by the Elastio Portal"
  sensitive   = true
  type        = string
  nullable    = false
}

variable "elastio_tenant" {
  description = "Name of your Elastio tenant. For example `mycompany.app.elastio.com`"
  type        = string
  nullable    = false
}

variable "elastio_cloud_connectors" {
  description = "List Cloud Connectors to deploy"
  type = list(object({
    region     = string
    vpc_id     = string
    subnet_ids = list(string)
  }))
  nullable = false
  default  = []
}

variable "elastio_nat_provision_stack" {
  description = <<DESCR
    Specifies the version of Elastio NAT provision stack to deploy (e.g. `v4`).

    This is a Cloudformation stack that provisions automatically provisions
    NAT Gateways in your VPC when Elastio worker instances run to provide them
    with the outbound Internet access when Elastio is deployed in private subnets.

    If you don't need this stack (e.g. you already have NAT gateways in your VPC
    or you deploy into public subnets) you can omit this parameter. The default
    value of `null` means there won't be any NAT provision stack deployed.

    The source code of this stack can be found here:
    https://github.com/elastio/contrib/tree/master/elastio-nat-provision-lambda
  DESCR
  type        = string
  nullable    = true
  default     = null
}
