# This template enables the S3 changelog for a single bucket.
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BucketName:
    Type: String
    AllowedPattern: .{3,}
    ConstraintDescription: Bucket name must be at least 3 characters long.
    Description: S3 bucket name.

  ScanExistingObjects:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: >
      If set to true, the full initial scan of the bucket will be performed.
      If set to false, only new objects in the bucket will be scanned.

  KeyPrefixes:
    # Unfortunately, it's impossible to pass CommaDelimitedList to a nested stack,
    # so we have to use String here, and then split it manually.
    Type: String
    AllowedPattern: ^(([^/,\s]+/)+)(,([^/,\s]+/)+)*$|^$
    ConstraintDescription: Prefixes must end (but not start) with '/', and cannot contain spaces.
    Description: >
      Comma-delimited list of prefixes of objects to scan. Note that, unless QRTS is enabled, paths selector
      in the Protection Policy will also be used to filter objects before scanning.

  EnableQrts:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: >
      If set to true, enables quasi-realtime scanning (QRTS).
      If set to false, disables QRTS.

  QrtsBatchSize:
    Type: Number
    Default: 100
    MinValue: 0
    Description: >
      Defines the number of S3 object updates that will be buffered in the queue before the scan job will be triggered.
      The lower this value is - the closer to real-time scanning you get, and the more expensive it becomes.

  QrtsMaxDelay:
    Type: Number
    Default: 300
    MinValue: 60
    Description: >
      Defines the maximum delay in seconds between the object update and its scan.
      The lower this value is - the closer to real-time scanning you get, and the more expensive it becomes.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: { default: "Main Parameters" }
        Parameters:
          - BucketName
          - ScanExistingObjects
          - KeyPrefixes
      - Label: { default: "Experimental Parameters" }
        Parameters:
          - EnableQrts
          - QrtsBatchSize
          - QrtsMaxDelay

Conditions:
  ScanExistingObjects: !Equals [!Ref ScanExistingObjects, 'true']
  EnableQrts: !Equals [!Ref EnableQrts, 'true']
  NoKeyPrefixes: !Equals [!Ref KeyPrefixes, '']

Resources:
  queue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days
      VisibilityTimeout: 3600 # 1 hour
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt dlq.Arn
        maxReceiveCount: 3
      Tags:
        - Key: elastio:resource
          Value: 'true'
        - Key: elastio:s3-changelog-bucket
          Value: !Ref BucketName
        - Key: elastio:s3-changelog-stack-arn
          Value: !Ref AWS::StackId

  dlq:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 30
      Tags:
        - Key: elastio:resource
          Value: 'true'
        - Key: elastio:s3-changelog-dlq
          Value: !Ref BucketName
        - Key: elastio:s3-changelog-stack-arn
          Value: !Ref AWS::StackId

  eventRule:
    Type: AWS::Events::Rule
    DependsOn: queue
    Properties:
      Description: !Sub Track S3 object change events in ${BucketName}
      EventPattern: !If
        - NoKeyPrefixes
        - !Sub >
          {
            "source": ["aws.s3"],
            "detail-type": ["Object Created", "Object Deleted"],
            "detail": { "bucket": { "name": ["${BucketName}"] } }
          }
        - !Join
          - ''
          - - !Sub >
              {
                "source": ["aws.s3"],
                "detail-type": ["Object Created", "Object Deleted"],
                "detail":
                {
                  "bucket": { "name": ["${BucketName}"] },
                  "object": { "key": [
            - !Sub
              - '{ "prefix": "${prefixes}" }'
              - prefixes: !Join
                - '" },{ "prefix": "'
                - !Split [',', !Ref KeyPrefixes]
            - '] } } }'
      Targets:
        - Arn: !GetAtt queue.Arn
          Id: changelog-queue
          InputTransformer:
            InputPathsMap:
              data: '$'
            InputTemplate:
              '{
                "kind": "S3Update",
                "data": <data>
              }'

  queueInlinePolicy:
    Type: AWS::SQS::QueueInlinePolicy
    Properties:
      Queue: !Ref queue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt queue.Arn
            Principal:
              Service: events.amazonaws.com
            Condition:
              ArnEquals:
                'aws:SourceArn': !GetAtt eventRule.Arn

  ssmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /elastio/s3/changelog/queue/${BucketName}/${queue.QueueName}
      Type: String
      Value: !Sub
        - >
          {
            "queue_url": "${queue}",
            "prefixes": [${prefixes}],
            "qrts": ${EnableQrts},
            "qrts_batch_size": ${QrtsBatchSize},
            "qrts_max_delay": ${QrtsMaxDelay}
          }
        - prefixes: !If
          - NoKeyPrefixes
          - ''
          - !Sub
            - '"${list}"'
            - list: !Join
              - '","'
              - !Split [',', !Ref KeyPrefixes]
      Tags:
        'elastio:resource': 'true'

  queueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableQrts
    Properties:
      AlarmDescription: !Sub Alarm if queue depth increases to more than ${QrtsBatchSize} messages
      ActionsEnabled: false
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt queue.QueueName
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: !Ref QrtsBatchSize
      ComparisonOperator: GreaterThanThreshold

  queueOldestMessageAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: EnableQrts
    Properties:
      AlarmDescription: !Sub Alarm if the age of the oldest massage is greater than ${QrtsMaxDelay} seconds.
      ActionsEnabled: false
      Namespace: AWS/SQS
      MetricName: ApproximateAgeOfOldestMessage
      Dimensions:
        - Name: QueueName
          Value: !GetAtt queue.QueueName
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: !Ref QrtsMaxDelay
      ComparisonOperator: GreaterThanThreshold

  alarmSubscription:
    Type: AWS::Events::Rule
    Condition: EnableQrts
    Properties:
      Description: Track S3 changelog Cloudwatch alarms state change for QRTS
      EventPattern:
        source: [aws.cloudwatch]
        detail-type: [CloudWatch Alarm State Change]
        resources:
          - !GetAtt queueDepthAlarm.Arn
          - !GetAtt queueOldestMessageAlarm.Arn
        detail:
          state:
            value: [ALARM]
      Targets:
        - Arn: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:elastio-scheduler-handler-s3-changelog-qrts'
          Id: event-handler
          Input: !Sub >
            {
              "bucket_name": "${BucketName}",
              "queue_url": "${queue}",
              "queue_name": "${queue.QueueName}"
            }

  scanExistingObjectsCustom:
    Type: Custom::ScanExistingObjects
    Condition: ScanExistingObjects
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:elastio-s3-changelog-handler-scan-existing-objects'
      QueueUrl: !Ref queue
      # We don't technically need key prefixes in the lambda,
      # but we want CFN to trigger an update if prefixes has changed.
      KeyPrefixes: !Ref KeyPrefixes

Outputs:
  queueArn:
    Value: !GetAtt queue.Arn
  dlqArn:
    Value: !GetAtt dlq.Arn
