# This file is not intended to be used on its own. It exists to work around a bug in CloudFormation.
# The bug prevents updating the CFN stack containing Fn::ForEach in the AWS console. This is because
# internally, CFN stores the template after resolving macros, so changing the input parameters has no effect.
# Related issue: https://github.com/aws-cloudformation/cfn-language-discussion/issues/146
AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions # for the Fn::ForEach function
Parameters:
  BucketNames:
    Type: String
  ScanExistingObjects:
    Type: String
    Default: 'false'
  EnableQrts:
    Type: String
    Default: 'false'
  KeyPrefixes:
    Type: String
Resources:
  'Fn::ForEach::Stacks':
    - BucketName
    - !Split [',', !Ref BucketNames]
    - 'stack&{BucketName}':
        Type: AWS::CloudFormation::Stack
        Properties:
          Parameters:
            BucketName: !Ref BucketName
            ScanExistingObjects: !Ref ScanExistingObjects
            EnableQrts: !Ref EnableQrts
            KeyPrefixes: !Ref KeyPrefixes
          TemplateURL: https://{{BUCKET}}.s3.{{REGION}}.amazonaws.com/{{PREFIX}}/{{VERSION}}/cloudformation-single.yaml
Outputs:
  templateVersion:
    Value: "{{VERSION}}"
